# Generated by Django 5.0.6 on 2024-05-14 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classinstance',
            name='weekday',
            field=models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], max_length=10),
        ),
    ]
