# Generated by Django 5.0.6 on 2024-05-28 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfa', '0002_alter_classinstance_weekday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classinstance',
            name='weekday',
            field=models.CharField(choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday'), ('7', 'Sunday')], max_length=10),
        ),
    ]
